server:
  port: 9999
  contextPath: /uaa
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
  path: ./logs
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: .*
spring:
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/portal?characterEncoding=utf-8&useSSL=false
    testWhileIdle: true
    validationQuery: SELECT 1
    username: portal
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
